micronaut:
  server:
    port: 8081
    context-path: "/shell"
  application:
    name: shell
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/shell/static/**"
        paths: "classpath:static"
  io:
    watch:
      paths: src/main
      restart: true
